import { School } from './types';

export const MOCK_SCHOOLS: School[] = [
  {
    id: "1",
    name: "Greenwood International High",
    udiseCode: "03010100101",
    image: "https://picsum.photos/400/300?random=1",
    state: "Punjab",
    district: "Bathinda",
    block: "Bathinda West",
    village: "Model Town",
    pincode: "151001",
    address: "Phase 3, Model Town, Bathinda",
    lat: 30.2104,
    lng: 74.9455,
    schoolStatusName: "Operational",
    yearDesc: "2024-25",
    estdYear: "1998",
    boardSecName: "CBSE",
    schTypeDesc: "Co-educational",
    schMgmtDesc: "Private Unaided",
    lowClass: 1,
    highClass: 12,
    bldStatus: "Private",
    mediumOfInstrName1: "English",
    clsrmsGd: 45,
    clsrmsMaj: 0,
    digiBoardTot: 15,
    projectorTot: 20,
    desktopFun: 40,
    laptopTot: 10,
    internetYnDesc: "Yes",
    electricityYnDesc: "Yes",
    libraryYnDesc: "Yes",
    playgroundYnDesc: "Yes",
    auditoriumYn: true,
    bndrywallType: "Pucca",
    fireSafetyYn: 1,
    medchkYnDesc: "Yes",
    rampsYn: 1,
    handrailsYn: 1,
    toiletbFun: 20,
    toiletbCwsnFun: 2,
    toiletgFun: 20,
    leadership: {
        principal: { name: "Mrs. S. Kaur" },
        sexualHarassmentCommitteeHead: { name: "Dr. Anjali Verma", designation: "Vice Principal" }
    },
    totalTeacher: 60,
    totTchPgraduateAbove: 45,
    tchReg: 55,
    tchCont: 5,
    rowTotal: 1500,
    rowGirlTotal: 700,
    rowBoyTotal: 800,
    profQual3: 58, // High B.Ed %
    tchRecvdServiceTrng: 50,
    stusHvFurnt: 1500, // 100% Furniture
    instructionalDays: 225,
    admissionFeeInRupees: 25000,
    tuitionFeeInRupees: 65000,
    yearlyDevelopmentChargesInRupees: 15000,
    annualMonthlyOtherCharges: 5000,
    principalName: "Mrs. S. Kaur"
  },
  {
    id: "2",
    name: "Govt Senior Secondary School",
    udiseCode: "03010100205",
    image: "https://picsum.photos/400/300?random=2",
    state: "Punjab",
    district: "Bathinda",
    block: "Rampura Phul",
    village: "Mehraj",
    pincode: "151103",
    address: "Main Road, Mehraj",
    lat: 30.2704,
    lng: 75.2455,
    schoolStatusName: "Operational",
    yearDesc: "2024-25",
    estdYear: "1975",
    boardSecName: "State Board",
    schTypeDesc: "Co-educational",
    schMgmtDesc: "Government",
    lowClass: 6,
    highClass: 12,
    bldStatus: "Government",
    mediumOfInstrName1: "Punjabi",
    mediumOfInstrName2: "English",
    clsrmsGd: 12,
    clsrmsMaj: 2,
    digiBoardTot: 2,
    projectorTot: 1,
    desktopFun: 5,
    laptopTot: 0,
    internetYnDesc: "Yes",
    electricityYnDesc: "Yes",
    libraryYnDesc: "Yes",
    playgroundYnDesc: "Yes",
    auditoriumYn: false,
    bndrywallType: "Pucca",
    fireSafetyYn: 0,
    medchkYnDesc: "No",
    rampsYn: 1,
    handrailsYn: 0,
    toiletbFun: 6,
    toiletbCwsnFun: 0,
    toiletgFun: 4,
    leadership: {
        principal: { name: "Mr. R. Singh" },
        sexualHarassmentCommitteeHead: { name: "Mrs. Kuldeep Kaur", designation: "Senior Lecturer" }
    },
    totalTeacher: 15,
    totTchPgraduateAbove: 10,
    tchReg: 12,
    tchCont: 3,
    rowTotal: 800,
    rowGirlTotal: 350,
    rowBoyTotal: 450,
    profQual3: 14,
    tchRecvdServiceTrng: 5,
    stusHvFurnt: 600, // Not 100%
    instructionalDays: 210,
    admissionFeeInRupees: 0,
    tuitionFeeInRupees: 0,
    yearlyDevelopmentChargesInRupees: 500,
    annualMonthlyOtherCharges: 0,
    principalName: "Mr. R. Singh"
  },
  {
    id: "1219528", // Using schoolId from JSON
    name: "St. Xavier's School Rampura Phul",
    udiseCode: "03140504402",
    image: "https://picsum.photos/400/300?random=3",
    state: "PUNJAB",
    district: "BATHINDA",
    block: "RAMPURA PHUL",
    village: "RAMPURA MANDI W-14",
    pincode: "151103",
    address: "St. Xavier High School Rampura Phul, By pass road Rampura Phul. Near Aggarwal Hospital Dist- Bathinda",
    lat: 30.274357,
    lng: 75.228174,
    schoolStatusName: "Operational",
    yearDesc: "2024-25",
    estdYear: "1994",
    boardSecName: "CBSE",
    schTypeDesc: "Co-educational",
    schMgmtDesc: "Private Unaided (Recognized)",
    lowClass: 1,
    highClass: 12,
    bldStatus: "Private",
    mediumOfInstrName1: "Punjabi", // Based on JSON ID 13
    clsrmsGd: 55,
    clsrmsMaj: 0,
    digiBoardTot: 40,
    projectorTot: 38,
    desktopFun: 58,
    laptopTot: 0,
    internetYnDesc: "Yes",
    electricityYnDesc: "Yes",
    libraryYnDesc: "Yes",
    playgroundYnDesc: "Yes",
    auditoriumYn: true, // Inferred from 'othrooms' > 0 or infrastructure context
    bndrywallType: "Pucca",
    fireSafetyYn: 1, // JSON has approachRoadYn: 1, assumes generic safety standard for example
    medchkYnDesc: "Yes",
    rampsYn: 1,
    handrailsYn: 0, // handrailsYn: 2 in JSON means No
    toiletbFun: 35,
    toiletbCwsnFun: 4,
    toiletgFun: 27,
    leadership: {
        principal: { 
            name: "Mr. Eulalio Julio Fernandes",
            contactNumber: "9780127298",
            email: "EULALFER10@GMAIL.COM",
            retirementDate: "10/12/28"
        },
        emergencyContactPerson: {
            name: "Eulalio Julio Fernandes",
            contactNumber: "9780127298",
            email: "EULALFER10@GMAIL.COM"
        },
        sexualHarassmentCommitteeHead: { 
            name: "Prem Lata", 
            email: "Prem@xavierrampura.com",
            contactNumber: "8360339412"
        }
    },
    totalTeacher: 82,
    totTchPgraduateAbove: 58,
    tchReg: 65,
    tchCont: 17,
    rowTotal: 2271,
    rowGirlTotal: 970,
    rowBoyTotal: 1301,
    profQual3: 56, // B.Ed qualified
    tchRecvdServiceTrng: 7, 
    stusHvFurnt: 2269, // Furniture
    instructionalDays: 219,
    
    // Fee Structure from JSON
    feeStructure: {
        primary: {
            admissionFeeInRupees: 1000,
            annualMonthlyOtherChargesForOtherFacilitiesInRupees: 4360,
            tuitionFeeInRupees: 37560,
            yearlyDevelopmentChargesInRupees: 41500
        },
        middle: {
            admissionFeeInRupees: 1000,
            annualMonthlyOtherChargesForOtherFacilitiesInRupees: 4940,
            tuitionFeeInRupees: 35640,
            yearlyDevelopmentChargesInRupees: 41500
        },
        secondary: {
            admissionFeeInRupees: 1000,
            annualMonthlyOtherChargesForOtherFacilitiesInRupees: 5346,
            tuitionFeeInRupees: 35640,
            yearlyDevelopmentChargesInRupees: 41500
        },
        seniorSecondary: {
            admissionFeeInRupees: 0,
            annualMonthlyOtherChargesForOtherFacilitiesInRupees: 4910,
            tuitionFeeInRupees: 38280,
            yearlyDevelopmentChargesInRupees: 5000
        }
    },
    // Flattened for compatibility with listing card sorting
    admissionFeeInRupees: 1000, 
    tuitionFeeInRupees: 37560, // Using Primary as baseline
    yearlyDevelopmentChargesInRupees: 41500,
    annualMonthlyOtherCharges: 4360,
    principalName: "Mr. Eulalio Julio Fernandes"
  },
  {
    id: "4",
    name: "New Horizon Public School",
    udiseCode: "03010100411",
    image: "https://picsum.photos/400/300?random=4",
    state: "Punjab",
    district: "Faridkot",
    block: "Kotkapura",
    village: "Kotkapura",
    pincode: "151204",
    address: "Faridkot Road",
    lat: 30.5800,
    lng: 74.8200,
    schoolStatusName: "Operational",
    yearDesc: "2024-25",
    estdYear: "2010",
    boardSecName: "CBSE",
    schTypeDesc: "Co-educational",
    schMgmtDesc: "Private Unaided",
    lowClass: 1,
    highClass: 12,
    bldStatus: "Private",
    mediumOfInstrName1: "English",
    clsrmsGd: 25,
    clsrmsMaj: 5,
    digiBoardTot: 5,
    projectorTot: 5,
    desktopFun: 15,
    laptopTot: 2,
    internetYnDesc: "Yes",
    electricityYnDesc: "Yes",
    libraryYnDesc: "Yes",
    playgroundYnDesc: "No",
    auditoriumYn: false,
    bndrywallType: "Barbed wire",
    fireSafetyYn: 0,
    medchkYnDesc: "Yes",
    rampsYn: 0,
    handrailsYn: 0,
    toiletbFun: 15,
    toiletbCwsnFun: 0,
    toiletgFun: 10,
    leadership: {
        principal: { name: "Mr. A. K. Gupta" },
        sexualHarassmentCommitteeHead: { name: "Mrs. Sharma", designation: "Coordinator" }
    },
    totalTeacher: 35,
    totTchPgraduateAbove: 15,
    tchReg: 20,
    tchCont: 15,
    rowTotal: 1200, // Very crowded
    rowGirlTotal: 500,
    rowBoyTotal: 700,
    profQual3: 30,
    tchRecvdServiceTrng: 30,
    stusHvFurnt: 1200,
    instructionalDays: 200,
    admissionFeeInRupees: 10000,
    tuitionFeeInRupees: 35000,
    yearlyDevelopmentChargesInRupees: 20000, // High dev fees relative to tuition
    annualMonthlyOtherCharges: 2000,
    principalName: "Mr. A. K. Gupta"
  }
];

export const DISTRICTS = ["Bathinda", "Faridkot", "Mansa", "Patiala", "Ludhiana"];